stages:
  - build

image: docker:latest

services:
  - docker:dind

variables:
  CI_REGISTRY: "registry.gitlab.com"
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}:latest"

build:
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker info
    - echo "Building ${CONTAINER_IMAGE} based on ${CONTAINER_IMAGE}"
    - docker buildx create --name mybuilder
    - docker buildx use mybuilder
    - docker buildx inspect --bootstrap
    - docker pull ${CONTAINER_IMAGE} || true
    - docker buildx build --platform linux/amd64,linux/arm64 --cache-from ${CONTAINER_IMAGE} --tag ${CONTAINER_IMAGE} --push .
  stage: build
  tags:
    - docker

